In [1]:
pip install numpy

Note: you may need to restart the kernel to use updated packages.


In [2]:
import numpy as np

In [3]:
# Criando um array

arr = np.array([1, 2, 3, 4, 5])

print(arr)

[1 2 3 4 5]


In [4]:
# Calculando o produto de um array

arr = np.array([1, 2, 3, 4, 5])

arr_produto = arr.dot(2)

print(arr_produto)

[ 2  4  6  8 10]


In [5]:
# Gerando uma matriz transposta

arr = np.array([[1, 2, 3], [4, 5, 6]])

print(np.transpose(arr))

[[1 4]
 [2 5]
 [3 6]]
